# -*- coding: utf-8 -*-
{   'active': False,
    'author': 'No author.',
    'category': u'base.module_category_knowledge_management',
    'data': [   u'security/academic_group.xml',
                u'view/division_view.xml',
                u'view/user_input_view.xml',
                u'view/group_view.xml',
                u'view/observation_category_view.xml',
                u'view/level_view.xml',
                u'view/group_evaluation_view.xml',
                u'view/period_view.xml',
                u'view/survey_view.xml',
                u'view/partner_view.xml',
                u'view/promotion_view.xml',
                u'view/section_view.xml',
                u'view/subject_view.xml',
                u'data/division_properties.xml',
                u'data/user_input_properties.xml',
                u'data/group_properties.xml',
                u'data/observation_category_properties.xml',
                u'data/level_properties.xml',
                u'data/group_evaluation_properties.xml',
                u'data/period_properties.xml',
                u'data/survey_properties.xml',
                u'data/partner_properties.xml',
                u'data/promotion_properties.xml',
                u'data/section_properties.xml',
                u'data/subject_properties.xml',
                u'data/division_track.xml',
                u'data/user_input_track.xml',
                u'data/group_track.xml',
                u'data/observation_category_track.xml',
                u'data/level_track.xml',
                u'data/group_evaluation_track.xml',
                u'data/period_track.xml',
                u'data/survey_track.xml',
                u'data/partner_track.xml',
                u'data/promotion_track.xml',
                u'data/section_track.xml',
                u'data/subject_track.xml',
                'security/ir.model.access.csv',
                u'view/academic_menuitem.xml'],
    'depends': [u'mail', u'survey'],
    'description': u'Academic',
    'installable': True,
    'license': 'AGPL-3',
    'name': u'Academic',
    'test': [],
    'version': '8.0.0.0.0',
    'website': ''}
# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
