# © 2016 ADHOC SA
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
{
    "name": "Academic Sale Subscription",
    "version": "19.0.1.2.0",
    "sequence": 14,
    "summary": "",
    "author": "ADHOC SA",
    "website": "www.adhoc.com.ar",
    "license": "AGPL-3",
    "depends": [
        "academic",
        "sale_subscription",
        "sale_subscription_ux",
        "crm",
        "sale_management",
        "account",
    ],
    "assets": {
        "web.assets_backend": [
            "academic_sale_subscription/static/src/client_actions/multi_print.js",
        ],
    },
    "data": [
        "data/ir_actions_server.xml",
        "data/ir_model_fields_data.xml",
        "security/ir.model.access.csv",
        "security/academic_security.xml",
        "report/report_data.xml",
        "data/mail_template.xml",
        "wizard/academic_order_wizard_views.xml",
        "wizard/update_payment_responsible_wizard_views.xml",
        "wizard/update_payment_responsible_partner_wizard_views.xml",
        "views/sale_order_views.xml",
        "views/res_partner_views.xml",
        "views/sale_subscription_views.xml",
        "views/sale_order_close_reason_views.xml",
        "views/res_config_settings_views.xml",
        "views/academic_group_views.xml",
        "views/account_move_views.xml",
        "views/account_move_line_views.xml",
        "views/product_template_views.xml",
        "views/account_portal_templates.xml",
        "views/portal_templates.xml",
        "views/debt_certificate_portal_templates.xml",
        "views/crm_lead_views.xml",
        "views/res_company_views.xml",
        "report/report_invoice.xml",
    ],
    "demo": [
        "demo/account_chart_demo.xml",
        "demo/account_journal_demo.xml",
        "demo/product_template_demo.xml",
        "demo/subscription_plan_demo.xml",
        "demo/sale_order_template_line_demo.xml",
        "demo/sale_order_close_reason_demo.xml",
        "demo/crm_lead_demo.xml",
        "demo/sale_subscription_demo.xml",
        "demo/account_move_demo.xml",
        "demo/website_contactus_demo.xml",
    ],
    "installable": True,
    "auto_install": ["sale_subscription", "academic"],
    "application": False,
    "post_init_hook": "post_init_hook",
}
