# © 2016 ADHOC SA
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
{
    "name": "Academic Sale Subscription",
    "version": "18.0.1.7.0",
    "sequence": 14,
    "summary": "",
    "author": "ADHOC SA",
    "website": "www.adhoc.com.ar",
    "license": "AGPL-3",
    "depends": [
        "academic",
        "sale_subscription",
        "sale_subscription_ux",
        "crm",
        "sale_management",
        "account",
    ],
    "data": [
        "data/ir_actions_server.xml",
        "security/ir.model.access.csv",
        "security/academic_security.xml",
        "views/sale_order_template_views.xml",
        "views/sale_subscription_plan_views.xml",
        "views/sale_order_views.xml",
        "wizard/academic_order_wizard_views.xml",
        "views/res_partner_views.xml",
        "views/sale_subscription_views.xml",
        "views/res_config_settings_views.xml",
        "views/academic_group_views.xml",
        "views/account_move_views.xml",
        "views/account_move_line_views.xml",
        "views/product_template_views.xml",
        "views/account_portal_templates.xml",
        "views/crm_lead_views.xml",
        "views/res_company_views.xml",
        "report/report_invoice.xml",
    ],
    "installable": True,
    "auto_install": ["sale_subscription", "academic"],
    "application": False,
    "post_init_hook": "post_init_hook",
}
